Vagrant.configure("2") do |config|
  config.vm.define "dapps" do |dapps|
    dapps.vm.box = "b9lab/eth_2020_06_22"
    dapps.vm.box_url = [
      "https://d3mgdk0lg98lr1.cloudfront.net/truffle-vagrant-package-2020-06-22.box",
      "https://b9-academy-assets.s3.amazonaws.com/public/boxes/truffle-vagrant-package-2020-06-22.box",
      "http://localhost:8080/ipfs/QmWBeXqjiqbU3HkLdi7mgSBrisvAfAV1UFtZGvzdJYpbKN",
      "http://ipfs.b9lab.com:8080/ipfs/QmWBeXqjiqbU3HkLdi7mgSBrisvAfAV1UFtZGvzdJYpbKN",
      "http://ipfs.io/ipfs/QmWBeXqjiqbU3HkLdi7mgSBrisvAfAV1UFtZGvzdJYpbKN"
    ]
    config.vm.box_download_checksum = "8012a4a04400f51677962ef0d4442b991ff01a8af9ac0865bd1a0ceb2feba5ec"
    config.vm.box_download_checksum_type = "sha256"
    # Change from "~/DAPPS" to an existing, and non-encrypted, folder on your host if the mount fails
    dapps.vm.synced_folder "~/DAPPS", "/home/vagrant/DAPPS", nfs: false, nfs_udp: false, create: true
    dapps.vm.network "private_network", type: "dhcp"
    dapps.vm.network :forwarded_port, guest: 8000, host: 8000, host_ip: "127.0.0.1"
    dapps.vm.network :forwarded_port, guest: 8545, host: 8545, host_ip: "127.0.0.1"

    # IPFS
    dapps.vm.network :forwarded_port, guest: 4001, host: 4001, host_ip: "127.0.0.1"
    dapps.vm.network :forwarded_port, guest: 5001, host: 5001, host_ip: "127.0.0.1"
    dapps.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "127.0.0.1"

    dapps.vm.provider "virtualbox" do |v|
      host = RbConfig::CONFIG['host_os']

      # Give VM 1/5 system memory & access to all cpu cores on the host
      if host =~ /darwin/
        cpus = `sysctl -n hw.ncpu`.to_i
        # sysctl returns Bytes and we need to convert to MB
        # mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 2
        mem = 3572
      elsif host =~ /linux/
        cpus = `nproc`.to_i
        # meminfo shows KB and we need to convert to MB
        # mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
        mem = 3572
      else # sorry Windows folks, I can't help you
        cpus = 2
        mem = 3572
      end

      v.customize ["modifyvm", :id, "--memory", mem]
      v.customize ["modifyvm", :id, "--cpus", cpus]
      v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
      v.customize ["modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, "ubuntu-focal-20.04-cloudimg-console.log")]
      v.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000]
    end

    dapps.vm.provision "file", source: "dotscreenrc", destination: "~/.screenrc"

    # dapps.vm.provision :shell, path: "bootstrap.sh"
  end
  # config.ssh.username = "ubuntu"
  # config.ssh.password = "cdce84730f0efe3c8bdf3638"
  # config.ssh.insert_key = false
end
